version: '3.8'
services:
  axon-server:
    image: axoniq/axonserver
    restart: always
    hostname:   axon-serve
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - '8081:8081'
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: pass
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: pass
        ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      depends_on:
        - mongo